version: '3.8'

services:
  db:
    image: postgres:15
    container_name: "${CONTAINER}"
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}}"
      POSTGRES_DB: "${NAME_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
